accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('unregister/', views.unregister, name='unregister'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.password, name='password'),
    path('<username>/', views.profile, name='profile'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    # read
    path('this_week/', views.this_week, name='this_week'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('history/', views.history, name='history'),

    # chapter related
    path('<int:subject_pk>/', views.chapter, name='chapter'),
    path('<int:subject_pk>/create_chapter/', views.create_chapter, name='create_chapter'),

    # article related
    path('<int:subject_pk>/<int:chapter_pk>/create/', views.create, name='create'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.delete, name='delete'),
    path('<int:article_pk>/vote/', views.vote, name='vote'),
    path('<int:article_pk>/pin/', views.pin, name='pin'),
]

cs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views as articles_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_views.index, name='index'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cs/templates/_error.html
{% if error %}
  <div class="alert alert-warning col" role="alert">
    {{ error }}
  </div>
{% endif %}

cs/templates/_nav_account.html
<li class="mb-1">

  {# 로그인 OK #}
  {% if request.user.is_authenticated %}
    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
      <li><a href="{% url 'accounts:profile' request.user.username %}" class="link-dark rounded">프로필</a></li>
      <li><a href="{% url 'accounts:edit' %}" class="link-dark rounded">개인정보수정</a></li>
      <li><a href="{% url 'accounts:logout' %}" class="link-dark rounded">로그아웃</a></li>
      <li><a href="#" class="link-dark rounded" data-bs-toggle="modal" data-bs-target="#unregisterModal">회원탈퇴</a></li>
    </ul>

  {# 로그인 NO #}
  {% else %}
    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
      <li><a href="{% url 'accounts:login' %}" class="link-dark rounded">로그인</a></li>
      <li><a href="{% url 'accounts:register' %}" class="link-dark rounded">회원가입</a></li>
    </ul>
  {% endif %}
</li>

cs/templates/_nav_article.html
{% for index_data in index_datas %}
  <li class="mb-1">
    {# subject toggle button #}
    {% if 'chapter' in request.resolver_match.route and the_subject.pk == index_data.subject.pk %}
      <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#{{ index_data.subject }}" aria-expanded="true">
        {{ index_data.subject }}
      </button>
    {% else %}
      <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#{{ index_data.subject }}" aria-expanded="false">
        {{ index_data.subject }}
      </button>
    {% endif %}

    {# subject toggle body #}
    <div class="collapse" id="{{ index_data.subject }}">
      <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
        <li><a class="link-dark text-decoration-none rounded" href="{% url 'articles:chapter' index_data.subject.pk %}">전체</a></li>
        {# chapter scrollspy #}
        {% for chapter in index_data.chapters %}
          <li><a class="link-dark text-decoration-none rounded" href="{% url 'articles:chapter' index_data.subject.pk %}#chapter-{{ chapter.pk }}">
            {{ chapter }}
          </a></li>
        {% endfor %}
      </ul>
    </div>
  </li>
{% endfor %}

cs/templates/_nav_home.html
<li>
  <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">
    홈 (작업중 미완)
  </button>

  <div class="collapse" id="home-collapse">
    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
      <li><a href="{% url 'articles:this_week' %}" class="link-dark rounded">이번주 주제글</a></li>
      <li><a href="{% url 'articles:upcoming' %}" class="link-dark rounded">다음주 주제글 투표</a></li>
      <li><a href="{% url 'articles:history' %}" class="link-dark rounded">이전 주제글</a></li>
    </ul>
  </div>
</li>

cs/templates/_nav_modal.html
{# unregister modal body #}
<div class="modal fade" id="unregisterModal" tabindex="-1" aria-labelledby="unregisterModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <h5 class="modal-title" id="unregisterModalLabel">정말 탈퇴하시겠습니까?</h5>
        
        <div class="mt-3 text-end">
          <button type="button" class="btn" data-bs-dismiss="modal">취소</button>
          <form action="{% url 'accounts:unregister' %}" method="POST" class="d-inline">
            {% csrf_token %}
            <button class="btn text-danger">회원탈퇴</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

cs/templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <link href="{% static 'sidebars.css' %}" rel="stylesheet">
  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/">
  <style>
    body, article {
      overflow: scroll;
    }

    .very-small li {
      margin: 14px;
      font-size: 14px;
      color: red;
    }

    .vote-emoji a {
      font-size: 1.2rem;
    }

    a.vote-emoji:hover,
    a.vote-emoji:focus {
      background-color: rgba(255, 255, 255, 0);
    }
  </style>
  <title>study_CS()</title>
</head>
<body>
  <div class="container my-4">
    <div class="row">

      {# navbar #}
      <nav class="col-3">
        {% include 'navbar.html' %}
      </nav>

      {# article #}
      <article class="col-9 mt-3">
        {# 에러메시지 #}
        {% include '_error.html' %}

        {# main article #}
        {% block content %}
        {% endblock content %}
      </article>

      {# footer #}
      <footer class="fixed-bottom border-top col-12 py-2 text-center bg-white">
        {% include 'footer.html' %}
      </footer>
    </div>
  </div>
  
  {% bootstrap_javascript %}
  <script src="https://kit.fontawesome.com/6255667e8c.js" crossorigin="anonymous"></script>
  <script src="{% static 'sidebars.js' %}"></script>
</body>
</html>

cs/templates/construction.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body class="container mt-5 pt-5">
  <h1>Sorry,<br> this page is now working on.</h1>
  <br><br><br><br><br>
  <a href="{% url 'index' %}" class="text-decoration-none link-dark">back to home</a>
  {% bootstrap_javascript %}
</body>
</html>

cs/templates/footer.html
<p class="small m-0 text-dark">
  Copyright&copy;2021 by <a class="text-decoration-none text-success" href="https://github.com/rootkwak528">root_kwak</a> & my classmates
</p>

cs/templates/navbar.html
{# this is navbar #}
<div class="p-3 ps-0 bg-white sticky-top" style="width: 320px;">

  {# logo #}
  <a href="{% url 'index' %}" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
    <span class="fs-5 fw-semibold">study_CS()</span>
  </a>
  
  {# menus #}
  <ul class="list-unstyled ps-0">

    {# home #}
    {% include '_nav_home.html' %}
    <li class="border-top my-3"></li>

    {# subject #}
    {% include '_nav_article.html' %}
    <li class="border-top my-3"></li>

    {# account #}
    {% include '_nav_account.html' %}
  </ul>
</div>

{% include '_nav_modal.html' %}

cs/templates/sidebar.html
<button class="btn btn-outline-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas">
  <i class="fas fa-bars"></i>
</button>


<div class="offcanvas offcanvas-end show" data-bs-scroll="true" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel">분야선택</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="#offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <p>Try scrolling the rest of the page to see this option in action.</p>
  </div>
</div>