accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('unregister/', views.unregister, name='unregister'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.password, name='password'),
    path('<username>/', views.profile, name='profile'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    # read
    path('this_week/', views.this_week, name='this_week'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('history/', views.history, name='history'),

    # chapter related
    path('<int:subject_pk>/', views.chapter, name='chapter'),
    path('<int:subject_pk>/create_chapter/', views.create_chapter, name='create_chapter'),

    # article related
    path('<int:subject_pk>/<int:chapter_pk>/create/', views.create, name='create'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.delete, name='delete'),
    path('<int:article_pk>/vote/', views.vote, name='vote'),
    path('<int:article_pk>/pin/', views.pin, name='pin'),
]

cs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views as articles_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_views.index, name='index'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    level = models.IntegerField(default=0)

    first_name = models.CharField(_('first name'), max_length=150)
    last_name = models.CharField(_('last name'), max_length=150)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from django.utils.translation import gettext, gettext_lazy as _


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name',)
        # exclude = ()


class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user_permissions = self.fields.get('user_permissions')
        if user_permissions:
            user_permissions.queryset = user_permissions.queryset.select_related('content_type')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.core.paginator import Paginator

from django.contrib.auth.views import login_required
from django.views.decorators.http import require_POST, require_http_methods, require_safe

from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm, CustomUserCreationForm

from .models import User

from articles.views import get_index_data


@require_http_methods(['GET', 'POST'])
def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect('index')
        else:
            form = AuthenticationForm()
            
        context = get_index_data()
        context.update({
            'form': form,
        })
        return render(request, 'accounts/form.html', context)
    else:
        return redirect('index')


@login_required
def logout(request):
    auth_logout(request)
    return redirect('index')


@require_http_methods(['GET', 'POST'])
def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                return redirect('index')
        else:
            form = CustomUserCreationForm()

        context = get_index_data()
        context.update({
            'form': form,
        })
        return render(request, 'accounts/form.html', context)
    else:
        return redirect('index')


@require_POST
def unregister(request):
    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=request.user.pk)
        auth_logout(request)
        user.delete()
    return redirect('index')


@login_required
@require_http_methods(['GET', 'POST'])
def edit(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    
    context = get_index_data()
    context.update({
        'form': form,
    })
    return render(request, 'accounts/form.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('index')
    else:
        form = PasswordChangeForm(request.user)
    
    context = get_index_data()
    context.update({
        'form': form,
    })
    return render(request, 'accounts/form.html', context)


@require_safe
def profile(request, username):
    user = get_object_or_404(User, username=username)
    
    # pagination - my_articles
    my_articles = user.my_articles.all()
    paginator_my = Paginator(my_articles, 5)
    page_number_my = request.GET.get('page_my')
    page_obj_my = paginator_my.get_page(page_number_my)

    # pagination - pinned_articles
    pinned_articles = user.pinned_articles.all()
    paginator_pin = Paginator(pinned_articles, 5)
    page_number_pin = request.GET.get('page_pin')
    page_obj_pin = paginator_pin.get_page(page_number_pin)

    context = get_index_data()
    context.update({
        'user': user,
        'page_obj_my': page_obj_my,
        'page_obj_pin': page_obj_pin,
    })
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/_article_list.html
<li class="list-unstyled border-top mb-3"></li>

<div class="row ms-3 pe-3 text-dark">
  <p class="fw-bold">{{ title }}</p>
  <ul class="list-group list-group-flush mb-2 ms-3">
    {% if page_obj|length %}
      {# article list #}
      {% for my_article in page_obj %}
        <li class="list-group-item">
          <a href="{% url 'articles:chapter' my_article.subject.pk %}" class="text-decoration-none small text-dark">
            {{ my_article.title|truncatechars:50 }}
          </a>
        </li>
      {% endfor %}

    {% else %}
      <li class="list-group-item small text-dark">{{ title }}가 없습니다.</li>
    {% endif %}
  </ul>

  {# paginator #}
  {% include 'accounts/_paginator.html' %}
</div>

accounts/templates/accounts/_paginator.html
{# paginator #}
<div class="d-flex justify-content-center mb-3">
  <ul class="list-group list-group-horizontal">
    {% if page_obj.number > 2 %}
      <li class="list-group-item border-0 px-2 py-0">
        <a class="small text-decoration-none text-dark" href="?{{ page }}=1">
          &laquo;
        </a>
      </li>
    {% endif %}

    {% if page_obj.has_previous %}
      <li class="list-group-item border-0 px-2 py-0">
        <a class="small text-decoration-none text-dark" href="?{{ page }}={{ page_obj.previous_page_number }}">
          {{ page_obj.previous_page_number }}
        </a>
      </li>
    {% endif %}

    <li class="list-group-item border-0 px-2 py-0">
      <span class="small text-decoration-none text-dark fw-bold" disabled>
        {{ page_obj.number }}
      </span>
    </li>
    
    {% if page_obj.has_next %}
      <li class="list-group-item border-0 px-2 py-0">
        <a class="small text-decoration-none text-dark" href="?{{ page }}={{ page_obj.next_page_number }}">
          {{ page_obj.next_page_number }}
        </a>
      </li>
    {% endif %}

    {% if page_obj.has_next and page_obj.next_page_number < page_obj.paginator.num_pages %}
      <li class="list-group-item border-0 px-2 py-0">
        <a class="small text-decoration-none text-dark" href="?{{ page }}={{ page_obj.paginator.num_pages }}">
          &raquo;
        </a>
      </li>
    {% endif %}
  </ul>
</div>

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  {% with request.resolver_match.url_name as url_name %}
    <div class="d-flex justify-content-between align-items-center pb-3 mb-3 link-dark border-bottom">
      <span class="fs-5 fw-semibold ms-3">
        {% if url_name == 'edit' %}
          개인정보수정
        {% elif url_name == 'login' %}
          로그인
        {% elif url_name == 'register' %}
          회원가입
        {% else %}
          {{ url_name }}
        {% endif %}
      </span>
    </div>
    
    <form action="" method="POST" class="my-4 ms-3">
      {% csrf_token %}
      {% bootstrap_form form %}
      
      <div class="d-flex justify-content-end">
        <div class="btn-group btn-group" role="group" aria-label="Basic checkbox toggle button group">
          {% if url_name == 'edit' %}
            <a href="{% url 'accounts:password' %}" class="btn btn-outline-dark">비밀번호변경</a>
            <button type="submit" class="btn btn-outline-dark">개인정보수정</button>

          {% elif url_name == 'login' %}
            <a href="{% url 'accounts:register' %}" class="btn btn-outline-dark">회원가입</a>
            <button type="submit" class="btn btn-outline-dark">로그인</button>

          {% elif url_name == 'register' %}
            <button type="submit" class="btn btn-outline-dark">회원가입</button>

          {% else %}
            <button type="submit" class="btn btn-outline-dark">{{ url_name }}</button>
            
          {% endif %}
        </div>
      </div>
    </form>
  {% endwith %}
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center pb-3 mb-3 link-dark border-bottom">
    <span class="fs-5 fw-semibold ms-3">
      프로필
    </span>
  </div>

  <div class="my-4">
    {# 기본정보 #}
    <div class="row ms-3 text-dark">
      {# 필드명 #}
      <div class="col-2">
        <p class="fw-bold">아이디</p>
        <p class="fw-bold">레벨</p>
        <p class="fw-bold">이름</p>
        <p class="fw-bold">이메일</p>
      </div>
      
      {# 레코드 #}
      <div class="col-10">
        <p class="">{{ user.username }}</p>
        <p class="">{{ user.level }}</p>
        <p class="">{{ user.last_name }} {{ user.first_name}} </p>
        <p class="">{{ user.email }}</p>
      </div>
    </div>

    {# 작성한 주제글 #}
    {% with title="작성한 주제글" page="page_my" page_obj=page_obj_my %}
      {% include 'accounts/_article_list.html' %}
    {% endwith %}

    {# 작성한 주제글 #}
    {% with title="저장한 주제글" page="page_pin" page_obj=page_obj_pin %}
      {% include 'accounts/_article_list.html' %}
    {% endwith %}

  </div>
{% endblock content %}