articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    # read
    path('this_week/', views.this_week, name='this_week'),
    path('upcoming/', views.upcoming, name='upcoming'),
    path('history/', views.history, name='history'),

    # chapter related
    path('<int:subject_pk>/', views.chapter, name='chapter'),
    path('<int:subject_pk>/create_chapter/', views.create_chapter, name='create_chapter'),

    # article related
    path('<int:subject_pk>/<int:chapter_pk>/create/', views.create, name='create'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.delete, name='delete'),
    path('<int:article_pk>/vote/', views.vote, name='vote'),
    path('<int:article_pk>/pin/', views.pin, name='pin'),
]

cs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views as articles_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_views.index, name='index'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articles/models.py
from django.db import models
from django.conf import settings


class Subject(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Chapter(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    title = models.CharField(max_length=20)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title}'


class Article(models.Model):
    # foreign keys
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='my_articles')
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='voted_articles', blank=True)
    pinner = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='pinned_articles', blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    # limit_choices_to = Chapter.objects.filter(subject=subject)
    # print(Chapter.objects.filter(subject=subject))
    # limit_choices_to = {'subject': True}
    # chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, limit_choices_to=limit_choices_to)

    # normal keys
    title = models.CharField(max_length=150)
    is_select = models.BooleanField(default=False)
    this_week = models.BooleanField(default=False) # 이번주 문제인가
    upcoming = models.BooleanField(default=False)  # 다음주 문제 후보인가
    history = models.BooleanField(default=False)   # 이전에 뽑혔던 문제인가
    select_week = models.CharField(max_length=20, blank=True)  # 언제 뽑혔는가
    answer = models.TextField(blank=True)  # 답안들
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # to be update
    # - markdown
    # https://github.com/agusmakmun/django-markdown-editor
    # https://github.com/agusmakmun/django-markdown-editor/wiki

    def __str__(self):
        return f'{self.subject} / {self.chapter} / {self.title}'

articles/forms.py
from django import forms
from .models import Article, Chapter


class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ('title', )


class ChapterForm(forms.ModelForm):
    
    class Meta:
        model = Chapter
        fields = ('title', )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.views import login_required
from django.views.decorators.http import require_POST, require_http_methods, require_safe

from .forms import ArticleForm, ChapterForm

from .models import Article, Chapter, Subject

from pprint import pprint
import random

max_vote = 2
index_images = [
    'https://images.unsplash.com/photo-1471180625745-944903837c22?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1467106130188-af373dea5412?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=564&q=80',
    'https://images.unsplash.com/photo-1497278090167-1a9312e6e74c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80',
    'https://images.unsplash.com/photo-1590421694065-7c56f3344c2f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NzB8fHJlbGF4fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    'https://images.unsplash.com/photo-1597822759274-7718de15a8b9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
    'https://images.unsplash.com/photo-1599579519578-d14054a6b57f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80',
    'https://images.unsplash.com/photo-1560172355-7aef0ac9eb6a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2732&q=80',
    'https://images.unsplash.com/photo-1583279697952-625317da8d00?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80',
    'https://images.unsplash.com/photo-1559613447-aa2ed3e6e6fa?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=704&q=80',
    'https://images.unsplash.com/photo-1584961630907-3fdb471c2848?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80',
]


def get_index_data():
    subjects = Subject.objects.all()
    index_datas = [{
        'subject': subject,
        'chapters': Chapter.objects.filter(subject=subject),
    } for subject in subjects]

    return {
        'index_datas': index_datas,
    }


def get_chapter_data(subject):
    chapters = Chapter.objects.filter(subject=subject)
    chapter_datas = [{
        'chapter': chapter,
        'articles': Article.objects.filter(chapter=chapter),
    } for chapter in chapters]

    return {
        'subject': subject,
        'chapter_datas': chapter_datas,
    }


@require_safe
def index(request):
    context = get_index_data()
    context.update({
        'image_path': random.choice(index_images),
    })
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create_chapter(request, subject_pk):
    # 권한 체크
    if request.user.level < 3:
        context = get_index_data()
        context.update({
            'error': '챕터 작성 권한이 없습니다. 관리자에게 문의하세요.',
        })
        return render(request, 'articles/index.html', context)

    if request.method == 'POST':
        form = ChapterForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.subject = get_object_or_404(Subject, pk=subject_pk)
            article.save()
            return redirect('articles:chapter', subject_pk)
    else:
        form = ChapterForm()
    subject = get_object_or_404(Subject, pk=subject_pk)
    context = get_index_data()
    context.update({
        'subject': subject,
        'form': form,
    })
    return render(request, 'articles/form.html', context)


@require_safe
def chapter(request, subject_pk):
    subject = get_object_or_404(Subject, pk=subject_pk)
    
    # context update
    context = get_index_data()
    context.update(get_chapter_data(subject))

    return render(request, 'articles/chapter.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request, subject_pk, chapter_pk):
    # 권한 체크
    if request.user.level < 2:
        context = get_index_data()
        context.update({
            'error': '문제 작성 권한이 없습니다. 관리자에게 문의하세요.',
        })
        return render(request, 'articles/index.html', context)

    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.subject = get_object_or_404(Subject, pk=subject_pk)
            article.chapter = get_object_or_404(Chapter, pk=chapter_pk)
            article.save()
            return redirect('articles:chapter', subject_pk)
    else:
        form = ArticleForm()
    chapter = get_object_or_404(Chapter, pk=chapter_pk)
    context = get_index_data()
    context.update({
        'chapter': chapter,
        'form': form,
    })
    return render(request, 'articles/form.html', context)


@login_required
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    chapter_pk = article.chapter.pk
    article.delete()
    return redirect('articles:chapter', f'#chapter-{chapter_pk}')


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            chapter_pk = article.chapter.pk
            form.save()
            return redirect('articles:chapter', f'#chapter-{chapter_pk}')
    else:
        form = ArticleForm(instance=article)
    context = get_index_data()
    context.update({
        'form': form,
    })
    return render(request, 'articles/form.html', context)


@login_required
@require_safe
def vote(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    # 권한 체크
    if request.user.level < 1:
        # context update
        context = get_index_data()
        context.update(get_chapter_data(article.subject))
        context.update({
            'error': '투표 권한이 없습니다. 관리자에게 문의하세요.',
        })
        return render(request, 'articles/chapter.html', context)

    # 투표 취소
    if article.voter.filter(pk=request.user.pk).exists():
        article.voter.remove(request.user)

    # 투표 추가
    else:
        if request.user.voted_articles.filter(chapter=article.chapter, is_select=False).count() < max_vote:
            article.voter.add(request.user)
        else:
            # context update
            context = get_index_data()
            context.update(get_chapter_data(article.subject))
            context.update({
                'error': f'최대 {max_vote}개까지만 투표할 수 있습니다.',
            })
            return render(request, 'articles/chapter.html', context)
    return redirect('articles:chapter', article.subject.pk)


@login_required
@require_safe
def pin(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    # 핀 취소
    if article.pinner.filter(pk=request.user.pk).exists():
        article.pinner.remove(request.user)

    # 핀 추가
    else:
        article.pinner.add(request.user)

    return redirect('articles:chapter', article.subject.pk)


def this_week(request):
    articles = Article.objects.filter(this_week=True)
    context = get_index_data()
    context.update({
        'articles': articles,
    })
    return render(request, 'articles/article_list.html', context)


def upcoming(request):
    articles = Article.objects.filter(upcoming=True)
    context = get_index_data()
    context.update({
        'articles': articles,
    })
    return render(request, 'construction.html', context)


def history(request):
    articles = Article.objects.filter(history=True)
    context = get_index_data()
    context.update({
        'articles': articles,
    })
    return render(request, 'construction.html', context)

articles/templates/articles/_vote.html
{# 활성화됐다면 #}
{% if action %}

  {# 이미 투표했다면 #}
  {% if voted %}
    <li class="list-group-item list-group-item-action list-group-item-success">
  {# 투표 안했다면 #}
  {% else %}
    <li class="list-group-item list-group-item-action">
  {% endif %}

      <div class="d-flex justify-content-between align-items-center">
        <div>
          {{ article.title }}

          {# 투표인 뱃지 #}
          <div style="margin-top:-4px">
            {% for voter in article.voter.all %}
              {% if voted %}
                <span class="badge bg-light text-success rounded-pill"><small>{{ voter.last_name }}{{ voter.first_name }}</small></span>
              
              {% else %}
                <span class="badge bg-light text-secondary rounded-pill"><small>{{ voter.last_name }}{{ voter.first_name }}</small></span>
              {% endif %}
            {% endfor %}
          </div>
        </div>

        <div>
          {# 투표 했다면 초록색 #}
          {% if voted %}
          
            {# 투표 버튼 #}
            <div class="text-center d-inline-block ms-2">
              {% if voted %}
                <a href="{% url 'articles:vote' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="fas fa-thumbs-up text-success"></i>
                </a>
              {% else %}
                <a href="{% url 'articles:vote' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="far fa-thumbs-up text-success"></i>
                </a><br>
              {% endif %}
            </div>
            
            {# 핀 버튼 #}
            <div class="text-center d-inline-block ms-2">
              {% if request.user in article.pinner.all %}
                <a href="{% url 'articles:pin' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="fas fa-bookmark text-success"></i>
                </a>
              {% else %}
                <a href="{% url 'articles:pin' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="far fa-bookmark text-success"></i>
                </a>
              {% endif %}
            </div>

          {# 안 했다면 회색 #}
          {% else %}
            {# 투표 버튼 #}
            <div class="text-center d-inline-block ms-2">
              {% if voted %}
                <a href="{% url 'articles:vote' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="fas fa-thumbs-up text-secondary"></i>
                </a>
              {% else %}
                <a href="{% url 'articles:vote' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="far fa-thumbs-up text-secondary"></i>
                </a><br>
              {% endif %}
            </div>
            
            {# 핀 버튼 #}
            <div class="text-center d-inline-block ms-2">
              {% if request.user in article.pinner.all %}
                <a href="{% url 'articles:pin' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="fas fa-bookmark text-secondary"></i>
                </a>
              {% else %}
                <a href="{% url 'articles:pin' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
                  <i class="far fa-bookmark text-secondary"></i>
                </a>
              {% endif %}
            </div>
          {% endif %}
        </div>
      </div>
    </li>

{# 활성화 안됐다면 #}
{% else %}
  <li class="list-group-item list-group-item-secondary text-black-50">
    <div class="d-flex justify-content-between align-items-center">
      <div>
        {{ article.title }}

        {# 투표인 뱃지 #}
        <div style="margin-top:-4px">
          {% for voter in article.voter.all %}
            <span class="badge bg-light text-black-50 rounded-pill"><small>{{ voter.last_name }}{{ voter.first_name }}</small></span>
          {% endfor %}
        </div>
      </div>

      <div>
        {# 핀 버튼 #}
        <div class="text-center d-inline-block ms-2">
          {% if request.user in article.pinner.all %}
            <a href="{% url 'articles:pin' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
              <i class="fas fa-bookmark text-black-50"></i>
            </a>
          {% else %}
            <a href="{% url 'articles:pin' article.pk %}" class="m-0 p-0 text-decoration-none vote-emoji">
              <i class="far fa-bookmark text-black-50"></i>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </li>

{% endif %}

articles/templates/articles/_votes.html
<ul class="btn-toggle-nav list-group ms-3">

  {# 투표할 문제 있는 경우 #}
  {% if chapter_data.articles|length > 0 %}

    {# 투표 문제 출력 #}
    {% for article in chapter_data.articles %}

      {# 비활성화된 투표는 버튼도 비활성화 #}
      {% if article.is_select %}
        {% with action=False %}
          {% include 'articles/_vote.html' %}
        {% endwith %}

      {# 활성화된 투표 #}
      {% else %}
        
        {# 투표 했다면 버튼 칠하고 뱃지 추가 #}
        {% if request.user in article.voter.all %}
          {% with action=True voted=True %}
            {% include 'articles/_vote.html' %}
          {% endwith %}

        {# 투표 안 했다면 버튼 초기화 #}
        {% else %}
          {% with action=True voted=False %}
            {% include 'articles/_vote.html' %}
          {% endwith %}
        {% endif %}

      {% endif %}
    {% endfor %}

  {# 투표할 문제 없는 경우 #}
  {% else %}
    <div class="my-1 text-center">
      등록된 문제가 없습니다.
    </div>
  {% endif %}
</ul>

articles/templates/articles/article_list.html
{% extends "base.html" %}

{% block content %}
  {% with request.resolver_match.url_name as url_name %}
    {# 제목 #}
    <div class="d-flex justify-content-between align-items-center pb-3 mb-3 link-dark border-bottom">
      <span class="fs-5 fw-semibold ms-3">
        {% if url_name == 'this_week' %}
          이번주 문제
        {% else %}
          {{ url_name }}
        {% endif %}
      </span>
    </div>

    {# 본문 (투표문제들) #}
    {% if articles|length > 0 %}
      {% for article in articles %}

        {% if url_name == 'this_week' %}
          {% with action=False %}
            {% include 'articles/_vote.html' %}
          {% endwith %}

        {% else %}
          {# tbd #}

        {% endif %}

      {% endfor %}

    
    {% else %}
      <div class="my-1 text-center">
        {% if url_name == 'this_week' %}
          아직 이번주 문제가 등록되지 않았습니다.

        {% else %}
          {# tbd #}

        {% endif %}
      </div>

    {% endif %}
  {% endwith %}
{% endblock content %}

articles/templates/articles/chapter.html
{% extends 'base.html' %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
    <span class="fs-5 fw-semibold ms-3">{{ subject }}</span>
    {% if request.user.level >= 3 %}
      <a href="{% url 'articles:create_chapter' subject.pk %}" class="small me-3 text-decoration-none text-success">새 챕터</a>
    {% endif %}
  </div>

  {# 문제 없으면 문구 출력 #}
  {% if chapter_datas|length == 0 %}
    <p class="text-danger fw-normal ms-3 ">아직 {{ subject }}에 등록된 챕터가 없습니다.</p>
  {% endif %}

  {# scrollspy #}
  <div data-bs-spy="scroll" data-bs-target="#scrollspy" data-bs-offset="0" class="scrollspy" tabindex="0">
    {% for chapter_data in chapter_datas %}
      <div class="border-bottom pb-3 mb-3">
        {# collapse button #}
        <div class="d-flex justify-content-between align-items-center">
          <button class="btn btn-toggle rounded" data-bs-toggle="collapse" data-bs-target="#chapter-{{ chapter_data.chapter.pk }}" aria-expanded="false" style="color: rgba(0, 0, 0, .65);">
            {{ chapter_data.chapter }}
          </button>
          {% if request.user.level >= 2 %}
            <a href="{% url 'articles:create' subject.pk chapter_data.chapter.pk %}" class="small me-3 text-decoration-none text-success">새 문제</a>
          {% endif %}
        </div>

        {# collapse items #}
        <div class="collapse mt-3" id="chapter-{{ chapter_data.chapter.pk }}">
          {% include 'articles/_votes.html' %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  {% with request.resolver_match.url_name as url_name %}
    <div class="d-flex justify-content-between align-items-center pb-3 mb-3 link-dark border-bottom">
      <span class="fs-5 fw-semibold ms-3">
        {% if url_name == 'create_chapter' %}
          {{ subject }} / 새 챕터 작성
        {% elif url_name == 'create' %}
          {{ chapter.subject }} / {{ chapter }} / 새 주제글 작성
        {% elif url_name == 'update' %}
          주제글 수정
        {% else %}
          {{ url_name }}
        {% endif %}
      </span>
    </div>
    
    <form action="" method="POST" class="my-4 ms-3">
      {% csrf_token %}
      {% bootstrap_form form %}
      
      <div class="d-flex justify-content-end">
        <div class="btn-group btn-group" role="group" aria-label="Basic checkbox toggle button group">
          {% if url_name == 'create_chapter' %}
            <button type="submit" class="btn btn-outline-dark">작성완료</button>

          {% elif url_name == 'create' %}
            <button type="submit" class="btn btn-outline-dark">작성완료</button>

          {% elif url_name == 'update' %}
            <button type="submit" class="btn btn-outline-dark">수정완료</button>

          {% else %}
            <button type="submit" class="btn btn-outline-dark">{{ url_name }}</button>
            
          {% endif %}
        </div>
      </div>
    </form>
  {% endwith %}
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <img class="img-fluid" src="{{ image_path }}" alt="bg-img">

  {% comment %} <ul class="list-group">
    {% for data in datas %}
      <a href="{% url 'articles:chapter' data.subject.id %}" class="list-group-item list-group-item-action">
        <li class="d-flex justify-content-between align-items-center">
          {{ data.subject.title }}
          <span class="badge bg-secondary rounded-pill">{{ data.subject.article_set.all|length }}</span>
        </li>
      </a>
    {% endfor %}
  </ul> {% endcomment %}
{% endblock content %}